const topics = [
    'Music',
    'Technology',
    'Fashion',
    'Sports',
    'Food',
    'Travel',
    'Fitness',
    'Health',
    'Finance',
    'Education',
    'Art',
    'Photography',
    'Gaming',
    'Books',
    'Movies',
    'Cars',
    'Politics',
    'History',
    'Science',
    'DIY',
    'Pets',
    'Gardening',
    'Meditation',
    'Cooking',
    'Beauty',
    'Parenting',
    'Relationships',
    'Home decor',
    'Environment',
    'Design',
    'Writing',
    'Business',
    'Psychology',
    'Spirituality',
    'Adventure',
    'Anime',
    'Comedy',
    'Crafts',
    'Language learning',
    'Fashion trends',
    'Fitness routines',
    'Health tips',
    'Personal finance',
    'Online education',
    'Contemporary art',
    'Nature photography',
    'Mobile gaming',
    'Classic literature',
    'Action movies',
    'Luxury cars',
    'Global politics',
    'Ancient history',
    'Space exploration',
    'Home improvement',
    'Organic gardening',
    'Mindfulness practices',
    'Gourmet cooking',
    'Skincare routines',
    'Modern parenting',
    'Dating advice',
    'Interior design',
    'Sustainable living',
    'Graphic design',
    'Fiction writing',
    'Start-up strategies',
    'Cognitive psychology',
    'Self-help books',
    'Yoga practices',
    'Outdoor adventures',
    'Manga culture',
    'Stand-up comedy',
    'Handmade crafts',
    'Language exchange',
    'Seasonal fashion',
    'Marathon training',
    'Mental health awareness',
    'Stock market analysis',
    'E-learning platforms',
    'Abstract art',
    'Wildlife photography',
    'Console gaming',
    'Fantasy literature',
    'Electric vehicles',
    'Geopolitical trends',
    'Medieval history',
    'Astrophysics',
    'Energy-efficient homes',
    'Herb gardening',
    'Vegan cooking',
    'Anti-aging skincare',
    'Positive parenting',
    'Relationship counseling',
    'Minimalist interiors',
    'Eco-friendly living',
    'Web design trends',
    'Non-fiction writing',
    'Entrepreneurship',
    'Behavioral economics',
    'Meditation techniques',
    'Backpacking tips',
    'Cosplay culture',
    'Satirical humor',
    'DIY projects',
    'Language proficiency',
    'Vintage fashion',
    'Crossfit workouts',
    'Nutritional science',
    'Personal budgeting',
    'Art history',
    'Portrait photography',
    'PC gaming',
    'Mystery novels',
    'Luxury watches',
    'Climate change policy',
    'Military history',
    'Quantum physics',
    'Smart home tech',
    'Vertical gardening',
    'Gluten-free recipes',
    'Skincare ingredients',
    'Blended families',
    'Conflict resolution',
    'Bohemian decor',
    'Green architecture',
    'User experience design',
    'Content marketing',
    'Cognitive behavioral therapy',
    'Wilderness survival',
    'Anime conventions',
    'Improv comedy',
    'Upcycling projects',
    'Translation services',
    'Seasonal fashion trends',
    'Marathon preparation',
    'Workplace wellness',
    'Investment strategies',
    'Online learning tools',
    'Renaissance art',
    'Landscape photography',
    'Virtual reality gaming',
    'Historical fiction',
    'Luxury travel',
    'Autonomous vehicles',
    'Dark matter research',
    'Passive solar homes',
    'Aromatherapy oils',
    'Paleo diet recipes',
    'Anti-aging treatments',
    'Positive discipline',
    'Marriage counseling',
    'Contemporary art galleries',
    'Sustainable fashion',
    'Adventure travel',
    'Comic book culture',
    'Stand-up specials',
    'DIY home decor',
    'Language teaching',
    'Street fashion',
    'Circuit training',
    'Holistic health',
    'Personal branding',
    'Economic policy',
    'Ancient civilizations',
    'Neuroscience',
    'Urban gardening',
    'Vegan baking',
    'Skincare routines',
    'Parenting styles',
    'Couples therapy',
    'Scandinavian design',
    'Online marketing',
    'Mindfulness meditation',
    'Backpacking gear',
    'Japanese culture',
    'Comedy writing',
    'Artisan crafts',
    'Translation services',
    'Seasonal gardening',
    'Triathlon training',
    'Workplace productivity',
    'Real estate investing',
    'Online education tools',
    'Contemporary sculpture',
    'Sports photography',
    'Virtual reality tours',
    'World War II history',
    'Space exploration',
    'Renewable energy',
    'Mediterranean diet',
    'Korean skincare',
    'Single parenting',
    'Relationship advice',
    'Industrial design',
    'Environmental policy',
    'DIY furniture',
    'Language immersion',
    'Fashion blogging',
    'Parkour training',
    'Mental wellness',
    'Personal development',
    'Political satire',
    'Historical reenactments',
    'Sustainable architecture',
    'Street photography',
    'Healthy eating habits',
    'Fashion design',
    'Athlete interviews',
    'Environmental activism',
    'Meditation retreats',
    'Adventure sports',
    'Anime art',
    'Sketch comedy',
    'Urban gardening',
    'Freelance writing',
    'Business management',
    'Behavioral psychology',
    'Survival skills',
    'Manga reviews',
    'Community gardening',
    'Digital nomad lifestyle',
    'Climate change research',
    'Art therapy',
    'Home brewing',
    'Cross-cultural communication',
    'Fashion illustration'
  ];